const express=require("express");
const router=express.Router();
const reg=require("./registration.js")
const login=require("./login.js")
const homePage=require("./homepage.js")
const kookoo=require("./kookoocube.js")
const ttt=require("./tictactoe.js")
const dt=require("./dynamicTable.js")
const et=require("./chessOfEvents.js")
const ds=require("./del_search.js")
const resultReport=require("./result_report.js")
const sorting=require("./sorting.js")
const filter=require("./searching_filter.js")
const job_app=require("./job_application.js")
const logout=require("./logout.js")
const api=require("./api_pagination.js")
const dqe=require("./dynamic_query.js")
router.use("/login",login)
router.use("/homePage",homePage)
router.use("/kookoo",kookoo)
router.use("/tictactoe",ttt)
router.use("/DT",dt)
router.use("/ET",et)
router.use("/delSearch",ds)
router.use("/result",resultReport)
router.use("/sorting",sorting)
router.use("/filter",filter)
router.use("/api",api)
router.use("/jobApp",job_app)
router.use("/logout",logout)
router.use("/dqe",dqe)
router.use("/",reg) 
module.exports=router